/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define PERIPHERAL_BASE_ADDRESS 	0x40000000

#define AHB_BASE_ADDRESS			(PERIPHERAL_BASE_ADDRESS + 0x00020000)

#define RCC_BASE_ADDRESS			(AHB_BASE_ADDRESS + 0x00001000)
#define IOPENR_ADDRESS				(RCC_BASE_ADDRESS + 0x0000002C)

#define IOPORT_ADDRESS				(PERIPHERAL_BASE_ADDRESS + 0x10000000)

#define GPIOA_BASE_ADDRESS			(IOPORT_ADDRESS + 0x00000000)
#define GPIOB_BASE_ADDRESS			(IOPORT_ADDRESS + 0x00000400)
#define GPIOC_BASE_ADDRESS			(IOPORT_ADDRESS + 0x00000800)

//GPIOA REGISTERS
#define GPIOA_MODER					(GPIOA_BASE_ADDRESS + 0x00000000)
#define GPIOA_OTYPER				(GPIOA_BASE_ADDRESS + 0x00000004)
#define GPIOA_OSPEEDR				(GPIOA_BASE_ADDRESS + 0x00000008)
#define GPIOA_IDR					(GPIOA_BASE_ADDRESS + 0x00000010)
#define GPIOA_ODR					(GPIOA_BASE_ADDRESS + 0x00000014)
//More registers 11 in total

//GPIOB REGISTERS
#define GPIOB_MODER					(GPIOB_BASE_ADDRESS + 0x00000000)
#define GPIOB_OTYPER				(GPIOB_BASE_ADDRESS + 0x00000004)
#define GPIOB_OSPEEDR				(GPIOB_BASE_ADDRESS + 0x00000008)


//GPIOA REGISTERS
#define GPIOC_MODER					(GPIOC_BASE_ADDRESS + 0x00000000)
#define GPIOC_OTYPER				(GPIOC_BASE_ADDRESS + 0x00000004)
#define GPIOC_OSPEEDR				(GPIOC_BASE_ADDRESS + 0x00000008)
#define GPIOC_IDR					(GPIOC_BASE_ADDRESS + 0x00000010)
#define GPIOC_ODR					(GPIOC_BASE_ADDRESS + 0x00000014)


//More registers 11 in total

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct
{
	uint32_t MODER;
	uint32_t OTYPER;
	uint32_t OSPEEDR;
	uint32_t PUPDR;
	uint32_t IDR;
	uint32_t ODR;
	uint32_t BSRR;
	uint32_t LCKR;
	uint32_t AFR[2];
	uint32_t BRR;
}GPIO_RegDef;

typedef struct
{
	uint32_t CR;
	uint32_t ICSCR;
	uint32_t CRRCR;
	uint32_t CFGR;
	uint32_t CIER;
	uint32_t CIFR;
	uint32_t CICR;
	uint32_t IOPRSTR;
	uint32_t AHBRSTR;
	uint32_t APB2RSTR;
	uint32_t APB1RSTR;
	uint32_t IOPENR;
	uint32_t AHBENR;
	uint32_t APB2ENR;
	uint32_t APB1ENR;
	uint32_t IOPSMENR;
	uint32_t AHBSMENR;
	uint32_t APB2MENR;
	uint32_t APB1MENR;
	uint32_t CCIPR;
	uint32_t CSR;
}RCC_RegDef;

typedef struct
{
	uint8_t reserved1;
	uint16_t CSSA;
	uint8_t reserved2;
	uint8_t reserved3;
	uint16_t IDR;
	uint8_t reserved4;
	uint32_t BSRR;
	uint32_t LCKR;
	uint32_t AFR[2];
	uint32_t BRR;
}FW_RegDef;


#define GPIOA  	((GPIO_RegDef*)GPIOA_BASE_ADDRESS)
#define GPIOB  	((GPIO_RegDef*)GPIOB_BASE_ADDRESS)
#define GPIOC  	((GPIO_RegDef*)GPIOC_BASE_ADDRESS)

#define RCC  	((RCC_RegDef*)RCC_BASE_ADDRESS)

int main(void)
{




	RCC->IOPENR |= 1<<0; //Enciendo CLK GPIOA

	RCC->IOPENR |= 1<<2; //Enciendo CLK GPIOC

	GPIOA->MODER &= ~(1<<11); //Config PA5 como output

	GPIOA->ODR |= 1<<5; //SET 1 en PA5
	GPIOA->ODR &= ~(1<<5); //SET 0 en PA5

	GPIOC->MODER &= ~(1<<26); //PC13 como input
	GPIOC->MODER &= ~(1<<27); //PC13 como input

	//*gpioc_idr



    /* Loop forever */
	while(1)
	{
		GPIOA->ODR &= ~(1<<5); // apago led
		delay_ms(1000);
		GPIOA->ODR |= 1<<5; //enciendo led
		delay_ms(1000);
		/*
		if(GPIOC->IDR & (1<<13))//mientras PC13 este high
		{
			GPIOA->ODR &= ~(1<<5); // apago led

		}
		else
		{
			GPIOA->ODR |= 1<<5; //enciendo led
		}
		*/

	}
}

void delay_ms(uint16_t n)
{
	uint16_t i;
	for(; n>0; n--)
		for(i=0; i<230;i++);
}
